"""API routes for memory conflict management and resolution."""

from enum import Enum
from http import HTTPStatus
from typing import Annotated, Any

from fastapi import APIRouter, Depends, Path, Query

from pydantic import BaseModel, Field

from backend.app.agents.memory import MemoryArchivistAgent
from backend.core.database import database

router = APIRouter(prefix="/memory/conflicts", tags=["memory_conflicts"])


# ---------------------------------------------------------------------------
# Enums & Models
# ---------------------------------------------------------------------------


class ConflictStatus(str, Enum):
    unresolved = "unresolved"
    reviewing = "reviewing"
    resolved_keep_a = "resolved_keep_a"
    resolved_keep_b = "resolved_keep_b"
    resolved_merged = "resolved_merged"
    dismissed = "dismissed"


class ConflictResolutionAction(str, Enum):
    keep_a = "keep_a"
    keep_b = "keep_b"
    merge = "merge"
    both = "both"
    dismiss = "dismiss"


class ConflictCreateRequest(BaseModel):
    """Request to create a conflict (usually auto-generated by system)."""

    fact_a_id: str = Field(..., min_length=1)
    fact_b_id: str = Field(..., min_length=1)
    conflict_type: str = Field("factual", pattern=r"^(factual|temporal|preferential)$")
    explanation: str | None = Field(None, max_length=500)


class ConflictResponse(BaseModel):
    """Full conflict record with both facts loaded."""

    id: str
    fact_a: dict[str, Any]
    fact_b: dict[str, Any]
    conflict_type: str
    explanation: str | None
    status: ConflictStatus
    resolution_notes: str | None
    detected_at: str
    resolved_at: str | None


class ListConflictsResponse(BaseModel):
    conflicts: list[ConflictResponse]
    total: int


class ResolveConflictRequest(BaseModel):
    action: ConflictResolutionAction
    resolution_notes: str | None = Field(None, max_length=1000)


class ProposeMergeResponse(BaseModel):
    merged_fact: str
    confidence: float
    proposed_category: str
    explanation: str


# ---------------------------------------------------------------------------
# Dependencies
# ---------------------------------------------------------------------------


async def get_current_user_id() -> str:
    """Placeholder for auth integration."""
    # TODO: Replace with actual JWT auth
    return "system"


UserId = Annotated[str, Depends(get_current_user_id)]


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get("", response_model=ListConflictsResponse)
async def list_conflicts(
    user_id: UserId,
    status_filter: ConflictStatus | None = Query(None, description="Filter by status"),
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
) -> dict[str, Any]:
    """List conflicts with optional status filter and pagination."""
    conflicts = await database.get_memory_conflicts(
        user_id=user_id, status_filter=status_filter, limit=limit, offset=offset
    )

    # Enrich with fact details for each conflict
    enriched = []
    agent = MemoryArchivistAgent()
    for c in conflicts:
        fact_a = await agent.retrieve(id=c["fact_a_id"])
        fact_b = await agent.retrieve(id=c["fact_b_id"])
        enriched.append(
            {
                "id": c["id"],
                "fact_a": fact_a,
                "fact_b": fact_b,
                "conflict_type": c["conflict_type"],
                "explanation": c["explanation"],
                "status": c["status"],
                "resolution_notes": c["resolution_notes"],
                "detected_at": c["detected_at"],
                "resolved_at": c["resolved_at"],
            }
        )

    total = await database.get_memory_conflict_count(user_id, status_filter)
    return {"conflicts": enriched, "total": total}


@router.post("/{conflict_id}/resolve", response_model=ConflictResponse)
async def resolve_conflict(
    conflict_id: str = Path(..., min_length=1),
    payload: ResolveConflictRequest,
    user_id: UserId,
) -> dict[str, Any]:
    """Resolve a conflict by taking an action."""
    # Verify conflict exists and is unresolved
    conflict = await database.get_memory_conflict(conflict_id, user_id)
    if not conflict or conflict["status"].startswith("resolved_") or conflict["status"] == "dismissed":
        raise ConflictNotFoundOrAlreadyResolved()

    # Run resolution logic based on action
    agent = MemoryArchivistAgent()
    fact_a = None
    fact_b = None

    match payload.action:
        case ConflictResolutionAction.keep_a:
            # Keep fact_a, soft-delete fact_b
            fact_b_id = conflict["fact_b_id"]
            await agent.delete(fact_b_id, soft=True)
            status = ConflictStatus.resolved_keep_a

        case ConflictResolutionAction.keep_b:
            # Keep fact_b, soft-delete fact_a
            fact_a_id = conflict["fact_a_id"]
            await agent.delete(fact_a_id, soft=True)
            status = ConflictStatus.resolved_keep_b

        case ConflictResolutionAction.merge:
            # Both facts partial truth - merge required
            # TODO: Implement merge UI flow
            status = ConflictStatus.reviewing

        case ConflictResolutionAction.both:
            # Both facts valid but complementary - keep both
            status = ConflictStatus.reviewing  # Needs user review for categories

        case ConflictResolutionAction.dismiss:
            # Not a real conflict
            status = ConflictStatus.dismissed

        case _:
            raise InvalidResolutionAction()

    # Update conflict status
    await database.update_memory_conflict_status(
        conflict_id=conflict_id,
        user_id=user_id,
        status=status.value,
        resolution_notes=payload.resolution_notes or f"Resolved via {payload.action.value}",
    )

    # Return updated conflict
    updated = await database.get_memory_conflict(conflict_id, user_id)
    if not updated:
        raise ConflictNotFound()

    return updated


@router.post("/{conflict_id}/propose_merge", response_model=ProposeMergeResponse)
async def propose_merge(
    conflict_id: str = Path(..., min_length=1), user_id: UserId
) -> dict[str, Any]:
    """Use ConflictResolverAgent to generate a merge proposal."""
    conflict = await database.get_memory_conflict(conflict_id, user_id)
    if not conflict:
        raise ConflictNotFound()

    # Retrieve both facts
    agent = MemoryArchivistAgent()
    fact_a = await agent.retrieve(id=conflict["fact_a_id"])
    fact_b = await agent.retrieve(id=conflict["fact_b_id"])

    # Let conflict resolver agent propose merged fact
    messages = [
        {
            "role": "system",
            "content": "You are a conflict resolution assistant. When given two facts in conflict, propose a merged fact that preserves the essential truths from both, resolves contradictions, and is concise.",
        },
        {
            "role": "user",
            "content": f"Fact A (type={fact_a['category']}): {fact_a['content']}\n"
            f"Fact B (type={fact_b['category']}): {fact_b['content']}\n\n"
            "Conflict explanation: {conflict['explanation']}\n\n"
            "Generate merged fact as JSON with fields:"
            '"merged_fact", "confidence" (0.0-1.0), "proposed_category", "explanation"',
        },
    ]

    result = ""
    async for chunk in complete_chat(messages, model="llama3.1", temperature=0.7):
        result += chunk.get("content", "")

    # Parse structured output
    try:
        import json
        import re

        json_match = re.search(r"\{.*\}", result, re.DOTALL)
        if json_match:
            merge_data = json.loads(json_match.group())
        else:
            raise ValueError("No valid JSON found in response")

        return {
            "merged_fact": merge_data.get("merged_fact", ""),
            "confidence": float(merge_data.get("confidence", 0.5)),
            "proposed_category": merge_data.get("proposed_category", "general"),
            "explanation": merge_data.get("explanation", "Auto-generated merge"),
        }

    except Exception as exc:
        logger.error("Failed to parse merge proposal: %s - result: %s", exc, result[:200])
        # Fallback: concatenate with clear attribution
        merged = f"Based on: {fact_a['content']} AND {fact_b['content']}"
        return {
            "merged_fact": merged,
            "confidence": 0.6,
            "proposed_category": conflict["conflict_type"],
            "explanation": "Fallback merge: preserving both facts",
        }


# ---------------------------------------------------------------------------
# HTTP Error Responses
# ---------------------------------------------------------------------------


class ConflictNotFound(Exception):
    def to_response(self) -> tuple[dict[str, Any], int]:
        return {"error": "Conflict not found"}, HTTPStatus.NOT_FOUND


class ConflictNotFoundOrAlreadyResolved(Exception):
    def to_response(self) -> tuple[dict[str, Any], int]:
        return {"error": "Conflict not found or already resolved"}, HTTPStatus.NOT_FOUND


class InvalidResolutionAction(Exception):
    def to_response(self) -> tuple[dict[str, Any], int]:
        return
{"error": "Invalid resolution action"},
HTTPStatus.BAD_REQUEST